### ISSUE TITLE
 Pretrained models unavailable

### ISSUE THREAD

**Issue by u517872i** [Rongjiehuang/TranSpeech#5]
The pretrained HiFi-GAN and dict.unit.txt links provided don't work anymore. Would you give new ones for convenience?

**Comment by 9seven** [comment]
@Rongjiehuang The pretrained HiFi-GAN and dict.unit.txt links are unavailable. Would you please update them? Thanks a lot!!!

**Comment by Rongjiehuang** [comment]
Hi, the link has been updated
