### ISSUE TITLE
Missing unit.dict.txt

### ISSUE THREAD

**Issue by Amanb0420** [Rongjiehuang/TranSpeech#6]
The provided download link leads to a file not found error page for the unit.dict.txt
![Screenshot 2024-06-19 194709](https://github.com/Rongjiehuang/TranSpeech/assets/67551824/06b1938e-5566-4591-bf82-bef51a6cfc08)

**Comment by Rongjiehuang** [comment]
please find here: https://huggingface.co/Rongjiehuang/TranSpeech/
